// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xeltjetjnpwyydkpwjxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlbHRqZXRqbnB3eXlka3B3anh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0MDY0MDUsImV4cCI6MjA1MTk4MjQwNX0.CFk1pzmcBh4YwsHqAitycIkAWCgM_rRzYW_RmxW573w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);